// Shared enums for the DAF application
// These match the string values used in the Prisma schema

export enum UserRole {
  DEALER_TECH = 'DEALER_TECH',
  DEALER_ADMIN = 'DEALER_ADMIN',
  MFG_QA = 'MFG_QA',
  MFG_ADMIN = 'MFG_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}

export enum UnitStatus {
  PENDING_PDI = 'PENDING_PDI',
  PDI_IN_PROGRESS = 'PDI_IN_PROGRESS',
  PDI_COMPLETE = 'PDI_COMPLETE',
  PDI_ISSUES = 'PDI_ISSUES',
  SHIPPED = 'SHIPPED',
  RECEIVED = 'RECEIVED',
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  IN_ACCEPTANCE = 'IN_ACCEPTANCE',
  ACCEPTANCE_IN_PROGRESS = 'ACCEPTANCE_IN_PROGRESS',
  ACCEPTED = 'ACCEPTED',
  ACCEPTED_WITH_CONDITIONS = 'ACCEPTED_WITH_CONDITIONS',
  CONDITIONALLY_ACCEPTED = 'CONDITIONALLY_ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum EventType {
  MANUFACTURED = 'MANUFACTURED',
  SHIPPED = 'SHIPPED',
  RECEIVED = 'RECEIVED',
  PDI_STARTED = 'PDI_STARTED',
  PDI_COMPLETED = 'PDI_COMPLETED',
  ACCEPTANCE_STARTED = 'ACCEPTANCE_STARTED',
  ACCEPTANCE_COMPLETED = 'ACCEPTANCE_COMPLETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  NOTE_ADDED = 'NOTE_ADDED',
}

export enum PdiStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETE = 'COMPLETE',
  INCOMPLETE = 'INCOMPLETE',
  ISSUES_PENDING = 'ISSUES_PENDING',
}

export enum ItemStatus {
  PENDING = 'PENDING',
  PASS = 'PASS',
  FAIL = 'FAIL',
  ISSUE = 'ISSUE',
  NA = 'NA',
}

export enum AcceptanceStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AcceptanceDecision {
  ACCEPTED = 'ACCEPTED',
  ACCEPTED_WITH_CONDITIONS = 'ACCEPTED_WITH_CONDITIONS',
  REJECTED = 'REJECTED',
  FULL_ACCEPT = 'FULL_ACCEPT',
  CONDITIONAL = 'CONDITIONAL',
  REJECT = 'REJECT',
}

export enum IssueSeverity {
  MINOR = 'MINOR',
  MAJOR = 'MAJOR',
  CRITICAL = 'CRITICAL',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
}

export enum PhotoType {
  GENERAL = 'GENERAL',
  ISSUE = 'ISSUE',
  BEFORE = 'BEFORE',
  AFTER = 'AFTER',
}
